[rocks]

[plugins]
"rocks.nvim" = "2.21.0"
"rocks-git.nvim" = "1.4.0"
"rocks-config.nvim" = "1.3.1"
"rocks-treesitter.nvim" = "scm"
catppuccin = { git = "catppuccin/nvim", name = "catppuccin" }
tree-sitter-lua = "scm"
neorg = "8.4.0"
tree-sitter-toml = "scm"
neogen = "2.17.1"
"oil.nvim" = "2.7.0"
tree-sitter-hyprlang = "scm"

[config]
plugin_dir = "fymyte/plugins/"
auto_setup = false
