-- require"fidget".setup {
--   text = { spinner = "dots_pulse" },
--   window = { relative = "editor" },
--   timer = { fidget_decay = 3000 },
--   sources = {
--     ['ltex'] = { ignore = true },
--   },
--   fmt = {
--     max_width = 32
--   }
-- }
