-- local ok, telescope = pcall(require, 'telescope')
-- if not ok then
--   return
-- end

-- local utils = require 'fymyte.utils'

-- telescope.setup {
--   defaults = {
--     theme = {
--       border = true,
--       borderchars = {
--         prompt = { '─', '│', ' ', '│', '╭', '╮', '│', '│' },
--         results = { '─', '│', '─', '│', '├', '┤', '╯', '╰' },
--         preview = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
--       },
--     },
--   },
--   pickers = {
--     current_buffer_fuzzy_find = { theme = 'dropdown' },
--     buffers = { theme = 'dropdown' },
--     registers = { theme = 'dropdown' },
--   },
--   extensions = {
--     file_browser = {
--       theme = 'dropdown',
--     },
--     project = {
--       base_dirs = {
--         '~/.config/nvim',
--       },
--       theme = 'dropdown',
--     },
--     ['ui-select'] = {
--       require('telescope.themes').get_dropdown {
--         -- even more opts
--       },
--     },
--   },
-- }

